### ISSUE TITLE
Firebase Email Authenticaion

### ISSUE THREAD

**Issue by nihanth876** [nihanth876/WERPApp#3]
We have to implement Email Authentication using Firebase for users who sign in by making use of the email address and password fields instead of signin with google. They should be getting a verification link to their email id specified and the verification link should validate the email address indeed belongs to the user.

Work starts after login UI is available

**Comment by and9roid** [comment]
I m ready to work on this 
-Mayuri

**Comment by ghost** [comment]
M ready to work on this.
-Mayuri
